development:
  adapter: postgresql
  host: localhost
  database: whats_happening_marketing_dev
  min_messages: warning

test:
  adapter: postgresql
  host: localhost
  database: whats_happening_marketing_test
  min_messages: warning

production:
  adapter: postgresql
  host: localhost
  database: whats_happening_marketing
  min_messages: warning